name: bloc_hooked_widget
description: A new Flutter package with simple BlocHookedWidget.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_hooks:
  hooked_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1